steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cx-bot', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cx-bot']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'cx-bot',
        '--image', 'gcr.io/$PROJECT_ID/cx-bot',
        '--platform', 'managed',
        '--region', 'europe-central2',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/cx-bot'
